### ISSUE TITLE
Issue while compiling 

### ISSUE THREAD

**Issue by RomainWilbert** [snipsco/rustling-ontology#107]
Hi Rustling team !

I have issues compiling latest version on Windows 10.

> Compiling rustling-ontology v0.17.0 (file:///C:/Users/romai/projects/rustling/rustling-ontology)
> error: failed to run custom build command for `rustling-ontology v0.17.0 (file:///C:/Users/romai/projects/rustling/rustling-ontology)`
> process didn't exit successfully: `C:\Users\romai\projects\rustling\rustling-ontology\target\debug\build\rustling-ontology-670eb07658abcf73\build-script-build` (exit code: 101)
> --- stdout
> cargo:rerun-if-changed=grammar/de/src/rules.rs
> 
> --- stderr
> thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: RustlingError(Msg("example: \"montag morgens\" matched no rule"), State { next_error: None })', libcore\result.rs:945:5
> note: Run with `RUST_BACKTRACE=1` for a backtrace.

Any hints ?

**Comment by RomainWilbert** [comment]
I had to comment the following training data for german language in order to compile :

 //example!(v, check_moment_span!(c, [2013, 2, 18, 3], [2013, 2, 18, 12]), "montag morgens");
 //example!(v, check_moment_span!(c, [2013, 2, 15, 3], [2013, 2, 15, 12]), "morgens am 15. februar", "15. februar morgens", "am morgen des 15. februar");
//example!(v, check_moment_span!(c, [2013, 2, 14, 9], [2013, 2, 14, 12]), "Donnerstag Vormittag von 9 bis 11");
//example!(v, check_moment_span!(c, [2013, 2, 12, 3], [2013, 2, 12, 12]), "in der früh", "am morgen");
//example!(v, check_moment!(c, [2013, 2, 12, 5, 30]), "in der nächsten Stunde");
//example!(v, check_moment_span!(c, [2013, 2, 12, 11], [2013, 2, 12, 13]), "kurz vor mittag", "am späten vormittag");
//example!(v, check_moment!(c, [2013, 2, 12, 11, 15]), "um viertel mittag");

**Comment by hdlj** [comment]
Hello Romain, This should be fixed now, we have done a major improvement in German and Japanese for the past weeks.
