### ISSUE TITLE
"error: failed to run custom build command for `crfsuite-sys v0.2.0-pre" While trying to set up snips-nlu on docker image 

### ISSUE THREAD

**Issue by ShreyankS** [snipsco/rustling-ontology#137]
# Parsing Error

## Version

rustc 1.31.0-nightly

`your.tag.number`

## Language

`your_language_code`

## Parser input

`your input here`

## Parser output

```
error: failed to run custom build command for `crfsuite-sys v0.2.0-pre (https://github.com/snipsco/crfsuite-rs?rev=30b2ea6#30b2ea6f)`
process didn't exit successfully: `/nff/tools/dack/target/release/build/crfsuite-sys-c76bddaf3c451c85/build-script-build` (exit code: 101)

Paste the output of the `rustling-cli` here
```
thread 'main' panicked at 'Unable to find libclang: "couldn\'t find any of [\'libclang.so\', \'libclang.so.*\', \'libclang-*.so\'], set the LIBCLANG_PATH environment variable to a path where one of these files can be found (skipped: [])"', libcore/result.rs:1009:5

## Parser expected output (Optional)

```
Paste the expected output of the `rustling-cli` here
```

**Comment by adrienball** [comment]
I'm closing this issue since it is not related to `rustling-ontology`. Feel free to re-open it on https://github.com/snipsco/snips-nlu-rs if you still have troubles with `crfsuite`.
