### ISSUE TITLE
Exclude quantifiers from JA number

### ISSUE THREAD

**Issue by ClemDoum** [snipsco/rustling-ontology#174]
# Parsing Error

## Version
`0.18.0`

## Language
`ja`

## Parser input
`二十足`

## Parser output
```
BuiltinEntity { value: "二十足", range: 0..3, entity: Number(NumberValue { value: 20.0 }), entity_kind: Number }
```

## Parser expected output (Optional)
```
BuiltinEntity { value: "二十", range: 0..2, entity: Number(NumberValue { value: 20.0 }), entity_kind: Number }
```
We expect Rustling not to output the quantifier in the number.
It seems that users exclude them from tagging (or are told to exclude them). This creates inconsistencies between what the user tags and what Rustling can recognize leaving the CRF without builtin entity match features, which makes it fail.

cc @mayukauenogayer

**Comment by ClemDoum** [comment]
@JohannaSimoens I'm not familiar enough with the discussion around builtin entities and quantifiers
I think the subject has been discussed a lot.
If you need to have more context, @davidleroy and @mayukauenogayer may be able to explain our choices

**Comment by rosastern** [comment]
@JohannaSimoens this is a pending task on our todo list. The main issue is that some japanese numbers are ambiguous with a sequence number + quantifier. So it's not really that our tagging includes the quantifier, rather that in some cases the tagged number is actually a (shorter) number followed by a quantifier (although I don't know if that applies to the example above, that needs to be checked), but the tagger is able to recognize a number there, so it does.

You can discuss with @Odile-deVismes  the possible solutions we had in mind, also relying on data provided by Mayuka, such as combinations which can ambiguous, their pronunciation and transcription. Indeed, some combinations are ambiguous only in writing, whereas pronunciation can lift the ambiguity, so wrong taggings wouldn't happen later on.

**Comment by JohannaSimoens** [comment]
Ok I'll have a look!

**Comment by mayukauenogayer** [comment]
To complement the description of the error, in this app, the chinese character "足" is used not as a quantifier, but a part of a verb "add". So obviously it's not tagged in the training sample, but NLU parse it as a single value of 20. There are many more exemples of these characters, which can be shared between quantifier and verb. So we have another reason to remove them from rustling. (It seems they are totally removed from LM).

**Comment by davidleroy** [comment]
Is it an urgent need ? We need to plan release date for this bug fix if it's critical

**Comment by Odile-deVismes** [comment]
Sorry, I forgot to add a comment yesterday. We fixed it yesterday.

**Comment by davidleroy** [comment]
We need a release to account for the rustling update. 
Next one is 1.2.2, code freeze next week. Adding this issue to the board. 
cc @ClemDoum

**Comment by rosastern** [comment]
Fix: https://github.com/snipsco/rustling-ontology/pull/176
