### ISSUE TITLE
"cinq cents" > "cinq"

### ISSUE THREAD

**Issue by pbaron** [snipsco/rustling-ontology#38]
Issue observed in the Carrefour demo.
ASR output: cinq cents grammes de fraises
Slots: cinq, grammes, fraises

# Parsing Error

## Version

`your.tag.number`

## Language

`your_language_code`

## Parser input

`your input here`

## Parser output

```
Paste the output of the `rustling-cli` here
```

## Parser expected output (Optional)

```
Paste the expected output of the `rustling-cli` here
```

**Comment by hdlj** [comment]
fix by #41
