### ISSUE TITLE
Add "demi", "dizaine", "douzaine", "quinzaine", "vingtaine", etc to the built-in Number slot

### ISSUE THREAD

**Issue by pbaron** [snipsco/rustling-ontology#39]
Right now if I input "une demi douzaine d'oeufs"
Only "une" gets detected. Not "demi douzaine"

# Parsing Error

## Version

`your.tag.number`

## Language

`your_language_code`

## Parser input

`your input here`

## Parser output

```
Paste the output of the `rustling-cli` here
```

## Parser expected output (Optional)

```
Paste the expected output of the `rustling-cli` here
```

**Comment by hdlj** [comment]
integrate by #41
