### ISSUE TITLE
[EN] Improve grammar snips/datetime for better sync with generative grammars

### ISSUE THREAD

**Issue by Garvys** [snipsco/rustling-ontology#42]
# Parsing Error

## Version

`7.0`

## Language

`en`

## Not parsed queries

- [x] on thursday march thirteen
- [x] twenty hours and an half hour from now
- [x] on monday november the first
- [x] fifteen hours and an half hour from now
- [ ] on august seventeenth two thousand and thirty-nine <b>(year too big)</b>
- [x] at oneish
- [ ] on thursday june thirty-one <b>(impossible date)</b>
- [x] at twoish
- [x] at tenish
- [x] on wednesday july the fourteenth
- [x] on saturday september eleventh
- [x] on saturday february five
- [x] nine weeks and a half from now
- [x] on monday november fifteen
- [x] on sunday december twelfth
- [x] twelve hours and an half hour from now
- [x] on wednesday january twelve
- [x] at dinner time
- [x] two hours and an half hour from now
- [x] on sunday march thirty
- [x] around tea time
- [x] on monday august thirtieth
- [x] on wednesday january nineteen
- [x] three and a half months from now
- [ ] since the end of the week
- [x] on thursday october twenty-eight
- [x] on monday march the seventeenth
- [x] four years and a half from now
- [x] by the end of the week
- [x] on saturday march eight
- [x] on saturday december twenty-five
- [x] nineteen hours and an half hour from now
- [ ] on august the seventeenth two thousand and forty <b>(year too big)</b>
- [x] on saturday july twenty-four
- [x] on thursday september the thirtieth
- [ ] on october the fourteenth two thousand and forty <b>(year too big)</b>
- [x] before the end of the week
- [x] during work
- [x] eleven weeks and a half from now
- [x] at twelveish
- [x] on friday november nineteen
- [x] one week and a half from now
- [ ] on friday november thirty-one <b> (impossible)</b>
- [x] on tuesday september seven
- [ ] on november twenty-third two thousand and forty <b> (impossible)</b>
- [x] on monday august sixteenth
- [x] on tuesday july sixth
- [x] on tuesday february the eighth
- [x] one hour and an half hour from now
- [ ] on monday june thirty-one <b>(impossible)</b>
- [x] eleven hours and an half hour from now
- [x] on sunday june twenty
- [x] twelve years and a half from now
- [x] on tuesday march the eleventh
- [ ] eleven and a half months from now
- [x] on friday september tenth
- [ ] on june the sixth two thousand and thirty-nine <b>(year too big)</b>
- [ ] on june tenth two thousand and forty <b>(year too big)</b>
- [x] on tuesday october five
- [ ] on april the twenty-fifth two thousand and forty <b>(year too big)</b>
- [x] on tuesday march four
- [ ] on may fourth two thousand and forty <b>(year too big)</b>
- [ ] until the end of the week
- [x] three weeks and a half from now
- [x] on saturday october thirtieth
- [x] six years and a half from now
- [x] on tuesday december twenty-one
- [x] on thursday april the twenty-second
- [x] sixteen hours and an half hour from now
- [x] on friday july two
- [x] on sunday october thirty-one
- [ ] eighteen hours and an half hour from now
- [x] on sunday february thirteenth
- [x] on sunday march the second
- [x] on sunday april thirty-one
- [ ] on may seventh two thousand and thirty-nine
- [x] twenty-six days and a half from now
- [ ] on february the twenty-ninth two thousand and thirty-nine
- [x] eleven years and a half from now
- [ ] on january the eighteenth two thousand and forty
- [x] on wednesday july twenty-eight
- [x] on sunday may the twenty-third
- [x] on wednesday april the second
- [x] on thursday january twenty
- [x] on tuesday december the twenty-eighth
- [x] four weeks and a half from now
- [x] on thursday january twenty-seventh
- [x] yesterday for lunch
- [ ] on october the twenty-eighth two thousand and forty
- [x] on sunday march sixteen
- [x] on friday september ten
- [x] ten weeks and a half from now
- [x] at fourish
- [x] on monday september the twentieth
- [x] two and a half months from now
- [x] on saturday august the seventh
- [x] on thursday june the tenth
- [x] thirteen hours and an half hour from now
- [x] on saturday may eight
- [x] on sunday june thirteen
- [x] one day and a half from now
- [ ] on may the twenty-sixth two thousand and forty
- [x] on saturday march the eighth
- [ ] around meal time
- [x] on saturday march twenty-two
- [ ] on tuesday august three
- [x] on thursday january the twenty-seventh
- [x] for first sunday of advent
- [ ] on september sixteenth two thousand and forty
- [ ] on september the thirtieth two thousand and thirty-nine
- [ ] on october the twenty-ninth two thousand and thirty-nine
- [x] on saturday october two
- [ ] on august twenty-ninth two thousand and thirty-nine
- [ ] nine years and a half from now
- [x] on saturday october thirty
- [x] on monday january three
- [ ] seven weeks and a half from now
- [x] one year and a half from now
- [ ] on april the twenty-ninth two thousand and forty <b>(year too big)</b>
- [x] on wednesday october twentieth
- [x] on thursday august the twelfth
- [x] eight weeks and a half from now
- [x] on tuesday december fourteen
- [x] nine hours and an half hour from now
- [x] on thursday december two
- [x] six hours and an half hour from now
- [x] at eightish
- [ ] on march the tenth two thousand and forty <b>(year too big)</b>
- [ ] on august seventh two thousand and forty <b>(year too big)</b>
- [x] ten hours and an half hour from now
- [x] on friday march fourteenth
- [ ] on november the nineteenth two thousand and thirty-nine <b>(year too big)</b>
- [x] on february thirtieth two thousand and twenty-two
- [x] at tea time
- [x] around dinner time
- [x] around supper time
- [ ] on july twenty-seventh two thousand and thirty-nine <b>(year too big)</b>
- [x] on friday january seven
- [ ] on february first two thousand and forty <b>(year too big)</b>
- [x] before work
- [ ] on sunday september twenty-six
- [x] two years and a half from now
- [ ] on saturday february twenty-six
- [x] twenty-three hours and an half hour from now
- [x] on sunday august the first
- [x] at supper time
- [x] at breakfast time
- [ ] on january sixth two thousand and forty <b>(year too big)</b>
- [ ] at sunrise
- [x] on sunday july four
- [x] five hours and an half hour from now
- [x] seven hours and an half hour from now
- [x] on friday december three
- [ ] seven years and a half from now
- [x] on tuesday june one
- [ ] on february the fourth two thousand and forty
- [ ] on may the third two thousand and thirty-nine <b>(year too big)</b>
- [x] at brunch time
- [x] at fiveish
- [x] four hours and an half hour from now
- [x] on thursday january twenty-seven
- [ ] on sunday november thirty-one
- [x] on tuesday february twenty-two
- [x] on friday april twenty-three
- [ ] on thursday january thirteen
- [ ] on november twenty-fourth two thousand and thirty-nine <b>(year too big)</b>
- [x] on wednesday march the fifth
- [x] on wednesday april nine
- [ ] twenty-one hours and an half hour from now
- [x] seventeen hours and an half hour from now
- [x] five years and a half from now
- [x] on monday august thirty
- [ ] on february the twenty-ninth two thousand and thirty-one <b>(impossible)</b>
- [x] twenty-two hours and an half hour from now
- [x] on monday march the third
- [ ] after the end of the week
- [x] on saturday december fourth
- [ ] on september the twentieth two thousand and thirty-nine <b>(year too big)</b>
- [x] on february thirtieth twenty seventeen
- [x] nine and a half months from now
- [ ] on sunday june the sixth
- [ ] on august the twenty-fifth two thousand and forty  <b>(year too big)</b>
- [x] on tuesday march the fourth
- [x] on tuesday november ninth
- [ ] at meal time
- [x] at threeish
- [x] at sixish
- [ ] on sunday november the twenty-eighth
- [x] at nineish
- [x] around breakfast time
- [x] twelve days and a half from now
- [ ] on april twenty-eighth two thousand and thirty-nine  <b>(year too big)</b>
- [x] on wednesday march twelve
- [x] five weeks and a half from now
- [x] at elevenish
- [ ] at sunset
- [x] on wednesday january the nineteenth
- [ ] on august the fourth two thousand and thirty-nine  <b>(year too big)</b>
- [x] around brunch time
- [x] at sevenish
- [x] at midday
- [ ] on september seventeenth two thousand and thirty-eight from one thirteen am to five twenty-three pm
- [x] on december sixteenth at eleven minutes past six
- [x] around fifteen twenty-three on june tenth twenty eighteen
- [x] from sevenish to tenish
- [x] at lunch time on thursday march the seventh

**Comment by hdlj** [comment]
#44
