### ISSUE TITLE
[FR] Improve grammar snips/datetime for better sync with generative grammars

### ISSUE THREAD

**Issue by Garvys** [snipsco/rustling-ontology#43]
## Version
`7.0`

## Language
`fr`

## Parser input

`your input here`

## Not parsed queries

- [x] à la fin de la journée
- [x] pour l'assomption
- [x] à l'heure du café
- [ ] à dix heures de l'après-midi
- [x] à l'heure du souper
- [x] cinquante-cinq heures quatorze minutes plus tard
- [x] pour la fête des mères
- [x] à l'heure du brunch
- [x] pour la fête des pères
- [x] au moment du thé
- [ ] à la tombée de la nuit
- [ ] à dix-huit heures passées de vingt-quatre de l'après-midi
- [ ] à douze heures passées de cinquante de l'après-midi
- [x] quarante heures neuf minutes plus tard
- [x] une heure trente minutes plus tard
- [ ] à la tombée du jour
- [x] au moment du petit-déjeuner
- [ ] au levé du soleil
- [x] pour la veille de noël
- [ ] à sept heures passées de une de l'après-midi
- [x] le dernier week-end du mois de décembre
- [x] cette nuit
- [ ] au levé du soleil
- [x] le dernier week-end du mois de janvier
- [x] pour pâques
- [x] pendant le travail
- [x] à treize heures passées de seize minutes
- [x] pour l'armistice
- [x] au moment du dîner
- [x] à vingt-trois heures passées de huit minutes
- [ ] au crépuscule
- [x] avant le travail
- [x] pour la fête nationale
- [x] à l'heure du goûter

**Comment by hdlj** [comment]
#41
